---
- name: Install and manage web services
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Setup NodeJS environment
  hosts: all
  become: true
  roles:
    - nodejs

- name: Configure web server with Apache, PHP, and PHP-MySQL
  hosts: webserver
  become: true
  roles:
    - apache_php

- name: Configure database server with MySQL
  hosts: database
  become: true
  roles:
    - mysql